[shell]
args = ["--cd ~"]
program = 'C:\Windows\System32\wsl.exe'

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono NF"

[font.bold]
family = "JetBrainsMono NF"

[font.italic]
family = "JetBrainsMono NF"

[font.bold_italic]
family = "JetBrainsMono NF"
